api = "0.2"

[buildpack]
  id = "takumakume/apt"
  name = "Apt Buildpack"
  version = "0.0.1"

[metadata]
  include_files = ["bin/build","bin/detect","buildpack.toml"]
  pre_package = "./scripts/package.sh"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
